### PR TITLE
Add learn modules to Opportunity Details UI

### PR DESCRIPTION
**Pull request by pxwxnvermx**
[Ticket](https://dimagi-dev.atlassian.net/browse/CCPC-104)

image

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
What does this look like with more modules? Can you do a screenshot with 10 or 11?

**Comment by pxwxnvermx** [comment]
@snopoke I replaced the cards with a table, with the cards the UI got cluttered with more than 10 modules.

**Review by snopoke — COMMENTED** [review]
What do you think about making this one of the tabs? Also, when you first create an opportunity these models won't be populated. It would be nice to add a placeholder - though we may need an extra data element so that we know if the app has been processed or not. (probably leave for another PR).

**Review by snopoke — APPROVED** [review]

**Comment by pxwxnvermx** [comment]
I think this would look better as a tab. But including this with the Learn Progress and Deliver Progress tabs does not make sense. We can make this a tab if in future we make changes to make an Opportunity have multiple deliver forms. Then the deliver forms and learn modules both can be individual tabs on the UI for Opportunity Details.

**Comment by snopoke** [comment]
> But including this with the Learn Progress and Deliver Progress tabs does not make sense.

Why don't you think it makes sense? I think it would be fine. But I'm not going to hold up this PR.

**Pull request merged**
